# Generated by Django 5.2.15 on 2026-06-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('sido', models.CharField(max_length=30, verbose_name='시/도')),
                ('sigungu', models.CharField(max_length=30, verbose_name='시/군/구')),
                ('dong', models.CharField(blank=True, max_length=30, verbose_name='읍/면/동')),
                ('region_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='지역 코드')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'regions',
                'ordering': ['sido', 'sigungu', 'dong'],
                'constraints': [models.UniqueConstraint(fields=('sido', 'sigungu', 'dong'), name='unique_region_sido_sigungu_dong')],
            },
        ),
    ]
