# Generated by Django 5.2.15 on 2026-06-23 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('fashion', '패션 정보 공유'), ('daily', '일상 & 소통'), ('local_shop', '우리 동네 가게'), ('experience', '체험단')], default='fashion', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('gender', models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('kids', '키즈')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('top', '상의'), ('bottom', '하의'), ('outer', '아우터'), ('shoes', '슈즈'), ('accessories', '잡화·악세사리'), ('lifestyle', '라이프스타일'), ('counseling', '고민·상담'), ('recruit', '체험단 모집'), ('review', '체험단 후기')], default='', max_length=20)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('store_name', models.CharField(blank=True, default='', max_length=100)),
                ('store_location', models.CharField(blank=True, default='', max_length=255)),
                ('product_description', models.TextField(blank=True, default='')),
                ('notice', models.TextField(blank=True, default='')),
                ('recruit_start', models.DateField(blank=True, null=True)),
                ('recruit_end', models.DateField(blank=True, null=True)),
                ('experience_end', models.DateField(blank=True, null=True)),
                ('experience_participation_start', models.DateField(blank=True, null=True)),
                ('experience_participation_end', models.DateField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='post_videos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='community.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('sns_account', models.CharField(blank=True, default='', max_length=100)),
                ('motivation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_applications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.post')),
            ],
            options={
                'unique_together': {('post', 'applicant')},
            },
        ),
    ]
