# Generated by Django 6.0.6 on 2026-06-12 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('gender', models.CharField(choices=[('all', '전체'), ('male', '남성'), ('female', '여성'), ('kids', '키즈')], default='all', max_length=10)),
                ('category', models.CharField(choices=[('top', '상의'), ('bottom', '하의'), ('outer', '아우터'), ('shoes', '슈즈'), ('accessories', '잡화·악세사리')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
