# Generated by Django 6.0.6 on 2026-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('fashion', '패션 정보 공유'), ('daily', '일상 & 소통')], default='fashion', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('top', '상의'), ('bottom', '하의'), ('outer', '아우터'), ('shoes', '슈즈'), ('accessories', '잡화·악세사리'), ('lifestyle', '라이프스타일'), ('counseling', '고민·상담')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('kids', '키즈')], max_length=10, null=True),
        ),
    ]
