# Generated by Django 5.2.15 on 2026-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_post_like_count_post_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceapplication',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=10),
        ),
    ]
