# Generated by Django 5.2.15 on 2026-06-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_hashtags_post_like_count_post_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('fashion', '패션 정보 공유'), ('daily', '일상 & 소통'), ('local_shop', '우리 동네 가게'), ('experience', '체험단 모집')], default='fashion', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
