# Generated by Django 5.2.15 on 2026-06-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_add_status_to_experienceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
