# Generated by Django 5.2.15 on 2026-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_hashtags_post_like_count_post_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
