# Generated by Django 5.2.15 on 2026-06-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_add_board_local_shop_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='experience_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='recruit_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='recruit_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('top', '상의'), ('bottom', '하의'), ('outer', '아우터'), ('shoes', '슈즈'), ('accessories', '잡화·악세사리'), ('lifestyle', '라이프스타일'), ('counseling', '고민·상담'), ('recruit', '체험단 모집'), ('review', '체험단 후기')], default='', max_length=20),
        ),
    ]
