# Generated by Django 5.2.15 on 2026-06-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_id'),
        ('community', '0006_add_experience_detail_fields'),
    ]

    operations = [
    ]
