# Generated by Django 6.0.6 on 2026-06-18 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '팔로우',
                'verbose_name_plural': '팔로우',
                'db_table': 'follows',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('business_email', models.EmailField(max_length=254, verbose_name='사업자 이메일')),
                ('business_name', models.CharField(max_length=100, verbose_name='상호명')),
                ('business_number', models.CharField(max_length=30, unique=True, verbose_name='사업자등록번호')),
                ('business_phone', models.CharField(max_length=20, verbose_name='사업장 전화번호')),
                ('owner_name', models.CharField(max_length=30, verbose_name='대표자명')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='사업장 주소')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사업자 프로필',
                'verbose_name_plural': '사업자 프로필',
                'db_table': 'business_profiles',
            },
        ),
        migrations.CreateModel(
            name='TermsAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('service_terms_agreed', models.BooleanField(default=False, verbose_name='서비스 이용약관 동의')),
                ('privacy_agreed', models.BooleanField(default=False, verbose_name='개인정보 수집 동의')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅 수신 동의')),
                ('service_terms_version', models.CharField(default='v1.0', max_length=20)),
                ('privacy_terms_version', models.CharField(default='v1.0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_agreement', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '약관 동의',
                'verbose_name_plural': '약관 동의',
                'db_table': 'terms_agreements',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user_type', models.CharField(choices=[('normal', '일반 사용자'), ('business', '사업자 사용자')], max_length=20, verbose_name='회원 유형')),
                ('real_name', models.CharField(max_length=30, verbose_name='실명')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='전화번호')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('N', '선택 안 함')], default='N', max_length=1, verbose_name='성별')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', through='accounts.Follow', through_fields=('follower', 'following'), to='accounts.userprofile', verbose_name='팔로잉')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to='accounts.userprofile', verbose_name='팔로우를 건 사용자'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='accounts.userprofile', verbose_name='팔로우 당한 사용자'),
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='지역 우선순위')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_regions', to='regions.region', verbose_name='지역')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to='accounts.userprofile', verbose_name='사용자 프로필')),
            ],
            options={
                'verbose_name': '사용자 선택 지역',
                'verbose_name_plural': '사용자 선택 지역',
                'db_table': 'user_regions',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='regions',
            field=models.ManyToManyField(related_name='user_profiles', through='accounts.UserRegion', to='regions.region', verbose_name='선택 지역'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_relation'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
        migrations.AddConstraint(
            model_name='userregion',
            constraint=models.UniqueConstraint(fields=('user_profile', 'region'), name='unique_user_profile_region'),
        ),
        migrations.AddConstraint(
            model_name='userregion',
            constraint=models.UniqueConstraint(fields=('user_profile', 'priority'), name='unique_user_profile_region_priority'),
        ),
        migrations.AddConstraint(
            model_name='userregion',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 3)), name='check_user_region_priority_1_to_3'),
        ),
    ]
