# Generated by Django 5.2.15 on 2026-06-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userregion_user_fk_and_selected_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_phone',
            field=models.CharField(max_length=20, verbose_name='사업자 전화번호'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to='accounts.userprofile', verbose_name='팔로우한 사용자'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='accounts.userprofile', verbose_name='팔로워 대상 사용자'),
        ),
        migrations.AlterField(
            model_name='termsagreement',
            name='service_terms_version',
            field=models.CharField(default='v1.0', max_length=20, verbose_name='서비스 약관 버전'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='accounts.Follow', through_fields=('follower', 'following'), to='accounts.userprofile', verbose_name='팔로우'),
        ),
    ]
