# Generated by Django 5.2.15 on 2026-06-23 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('external_store_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='외부 상가업소번호')),
                ('name', models.CharField(max_length=200, verbose_name='상호명')),
                ('branch_name', models.CharField(blank=True, default='', max_length=100, verbose_name='지점명')),
                ('category_code', models.CharField(blank=True, default='', max_length=20, verbose_name='업종 코드')),
                ('category_name', models.CharField(blank=True, default='', max_length=100, verbose_name='업종명')),
                ('jibun_address', models.CharField(blank=True, default='', max_length=255, verbose_name='지번 주소')),
                ('road_address', models.CharField(blank=True, default='', max_length=255, verbose_name='도로명 주소')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='위도')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='전화번호')),
                ('description', models.TextField(blank=True, default='', verbose_name='가게 소개')),
                ('opening_hours', models.TextField(blank=True, default='', verbose_name='영업시간')),
                ('website_url', models.URLField(blank=True, default='', max_length=500, verbose_name='웹사이트 주소')),
                ('view_count', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='조회수')),
                ('data_source', models.CharField(blank=True, default='', max_length=100, verbose_name='데이터 출처')),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='accounts.businessprofile', verbose_name='관리 사업자')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='regions.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'db_table': 'stores',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['region', 'is_active'], name='stores_region_active_idx'), models.Index(fields=['category_code'], name='stores_category_idx'), models.Index(fields=['name'], name='stores_name_idx')],
            },
        ),
    ]
