# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="view_count",
            field=models.PositiveBigIntegerField(
                default=0,
                db_index=True,
                verbose_name="조회수",
            ),
        ),
    ]

