# Generated by Django 5.2.15 on 2026-06-24 08:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalColorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('result_type', models.CharField(choices=[('spring_warm', '봄 웜톤'), ('summer_cool', '여름 쿨톤'), ('autumn_warm', '가을 웜톤'), ('winter_cool', '겨울 쿨톤')], db_index=True, max_length=20)),
                ('result_subtype', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('summary', models.TextField()),
                ('best_colors', models.JSONField(default=list)),
                ('avoid_colors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=dict)),
                ('analysis_metrics', models.JSONField(blank=True, default=dict)),
                ('provider_name', models.CharField(blank=True, default='', max_length=50)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_color_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_color_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pcolor_user_created_idx'), models.Index(fields=['result_type'], name='pcolor_result_type_idx')],
            },
        ),
    ]
